basic:
    name: AFS
    environments:
        production: 'https://www.castingsource.com/'
        staging: 'https://test-metal-casting-design-purchasing.pantheonsite.io/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - index.php/issues/marchapril-2025
        - index.php/advertising
        - index.php/articles/industry-news
        - index.php/metalcaster-directory
        - index.php/photo-galleries
        - index.php/columns
        - index.php/subscribe
        - index.php/casting-competition
        - index.php/issues/metalcaster-prospectus-2023
        - articles/2025/03/21/casting-stronger-bonds-why-manufacturer-foundry-relationships-matter
        - column/alternatives-arm-wrestling
        - index.php/contact-us
        - index.php/privacy-policy
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
